### ISSUE TITLE
Bounds order while using hquadrature

### ISSUE THREAD

**Issue by rpetit** [JuliaMath/HCubature.jl#23]
Hi,
I noticed some weird behaviour while using `hquadrature`:
`hquadrature(t->1, 0, -1)[1]` outputs 1, while, mathematically speaking, it should be -1. Is this intended, or does anybody have an idea of why is this happening ?

Thank you in advance for your help !

**Comment by stevengj** [comment]
Yes, it seems like the calls to `abs` on [this line](https://github.com/stevengj/HCubature.jl/blob/0d89f668d8de101d5d6d6b275cbbe8a31a3bfb9d/src/gauss-kronrod.jl#L43) and [this line](https://github.com/stevengj/HCubature.jl/blob/master/src/genz-malik.jl#L118) may be undesirable.  (In the latter case we will have to add `abs` calls to the `Δ[i] > Δ[kdivide]` check, however.)

A PR with a test would be welcome.

**Comment by rpetit** [comment]
Thanks, I'll see if I can find some time to come up with a PR !

**Comment by aakhmetz** [comment]
*** I spent all night from midnight to 5am trying to figure out the mistake in a complicated but working program

>> quadgk(x -> (gammacdf(shape, scale, S_R-x) - gammacdf(shape, scale, S_L-x)), E_L, S_L, rtol=ε)[1] 
gave -2.724235379524588
>>hquadrature(x -> (gammacdf(shape, scale, S_R-x) - gammacdf(shape, scale, S_L-x)), E_L, S_L, rtol=ε)[1] 
gave 2.724235379524588

Thank you very much!

**Comment by aakhmetz** [comment]
It looks like I did update my Julia packages, but Jupyter notebook was not updated. I am sorry for disturbing - it looks working perfectly now
