### ISSUE TITLE
Any plans to add Symbolics.jl inside HCubature.jl?

### ISSUE THREAD

**Issue by NoelAraujo** [JuliaMath/HCubature.jl#39]
I have more a question/suggestion than an issue.

Does `HCubature.jl` will get more features if it incorporates `Symbolics.jl`? 

The scenario that comes to my mind are Double Integrals, https://github.com/JuliaMath/HCubature.jl/issues/16 - I imagine that `Symbolics.jl` could perform the change of variables and Jacobian to solve the problem.

Thank you.

**Comment by stevengj** [comment]
No, Hcubature is much lower level than Symbolics. You might make a package that depends on both to do integrals over oddly shaped domains, but I don’t think I’ll ever want that in HCubature itself.
