### ISSUE TITLE
Did the behaviour change when integral limits are switched?

### ISSUE THREAD

**Issue by zhyiyu** [JuliaMath/HCubature.jl#67]
Hi, I used to remember that if I switch the upper and lower integral limits, the integral value does not change. That is to say, in the following:

```julia
function integrand(x_vector::Vector{Float64})
    return x_vector[1]
end

result_a = hcubature(integrand, [x_low], [x_up], rtol = 1e-5)[1]
result_b = hcubature(integrand, [x_low], [x_up], rtol = 1e-5)[1]
```

we will have `result_a = result_b` (OLD behaviour). However, recently I noticed that this behaviour has been changed at some point, namely `result_a = -result_b` (NEW behaviour). Is this true or did my memory deceive me?

BTW, the new behaviour is better, it is what people would expect.

**Comment by stevengj** [comment]
Yes, this was fixed in #57.
