### ISSUE TITLE
Concurrent caching and thread safety

### ISSUE THREAD

**Issue by kbarros** [JuliaMath/HCubature.jl#69]
Running HCubature on multiple threads can trigger a concurrent write error on this Dict:
https://github.com/JuliaMath/HCubature.jl/blob/6003c00e65aa6d7312c40262806862cba3256946/src/gauss-kronrod.jl#L10-L12

Our group has also encountered occasional segfaults when running HCubature on multiple threads, and I wonder if it's related.

Perhaps https://github.com/wherrera10/ThreadSafeDicts.jl could be considered?

**Comment by stevengj** [comment]
Or I could just put a lock around it.  We only access this dictionary once per call, so it should be a big overhead.

Note that QuadGK.jl has a similar cache: https://github.com/JuliaMath/QuadGK.jl/blob/e014f648573517879096025fc9d544eb45fa9467/src/gausskronrod.jl#L598-L600

**Comment by kbarros** [comment]
I agree. It looks like [ThreadSafeDicts](https://github.com/wherrera10/ThreadSafeDicts.jl) is essentially just this: A spinlock wrapping a normal Dict. Here is their [`get!` implementation](https://github.com/wherrera10/ThreadSafeDicts.jl/blob/master/src/ThreadSafeDicts.jl#L121-L143), which might be all that's needed here?

**Comment by stevengj** [comment]
I think we probably want a `ReentrantLock` rather than a spin-lock, because we want to hold the lock while the rule is computed, which might take a while.  If you call `get!` with an expensive `f()`, then you'll hold the lock too long.
